server:
  port: 8082

spring:
  application:
    name: board-service
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/boards_db
    username: myuser
    password: mypassword
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
