server:
  port: 8082

spring:
  application:
    name: board-service
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/boards_db
    username: myuser
    password: mypassword
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

resilience4j:
  retry:
    instances:
      myRetry:
        max-attempts: 3
        wait-duration: 2s
  circuitbreaker:
    instances:
      myCircuitBreaker:
        register-health-indicator: true
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c
    zipkin:
      enabled: true
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [service_name:${spring.application.name:-},trace_id:%X{traceId:-},span_id:%X{spanId:-}]"