server:
  port: 8082

spring:
  application:
    name: board-service
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/boards_db
    username: myuser
    password: mypassword
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

resilience4j:
  retry:
    instances:
      myRetry:
        max-attempts: 3
        wait-duration: 2s
  circuitbreaker:
    instances:
      myCircuitBreaker:
        register-health-indicator: true
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
